# Generated by Django 4.2.3 on 2024-11-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_topic_users_webpage_accessrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
