# Generated by Django 4.2.3 on 2024-10-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('email_add', models.EmailField(max_length=264, unique=True)),
                ('email_add_conf', models.EmailField(max_length=264, unique=True)),
                ('pw1', models.CharField(max_length=16)),
                ('pw2', models.CharField(max_length=16)),
            ],
        ),
    ]
